<?php

namespace Database\Seeders;

use App\Models\University;
use Illuminate\Database\Seeder;

class UniversitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $universities = [
            ['name' => 'Abdullah Gül Üniversitesi', 'email_domain' => 'agu.edu.tr'],
            ['name' => 'Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi', 'email_domain' => 'atu.edu.tr'],
            ['name' => 'Adıyaman Üniversitesi', 'email_domain' => 'adiyaman.edu.tr'],
            ['name' => 'Afyon Kocatepe Üniversitesi', 'email_domain' => 'aku.edu.tr'],
            ['name' => 'Afyonkarahisar Sağlık Bilimleri Üniversitesi', 'email_domain' => 'afsu.edu.tr'],
            ['name' => 'Ağrı İbrahim Çeçen Üniversitesi', 'email_domain' => 'agri.edu.tr'],
            ['name' => 'Akdeniz Üniversitesi', 'email_domain' => 'akdeniz.edu.tr'],
            ['name' => 'Aksaray Üniversitesi', 'email_domain' => 'aksaray.edu.tr'],
            ['name' => 'Alanya Alaaddin Keykubat Üniversitesi', 'email_domain' => 'alanya.edu.tr'],
            ['name' => 'Amasya Üniversitesi', 'email_domain' => 'amasya.edu.tr'],
            ['name' => 'Anadolu Üniversitesi', 'email_domain' => 'anadolu.edu.tr'],
            ['name' => 'Ankara Hacı Bayram Veli Üniversitesi', 'email_domain' => 'hbv.edu.tr'],
            ['name' => 'Ankara Müzik ve Güzel Sanatlar Üniversitesi', 'email_domain' => 'mgu.edu.tr'],
            ['name' => 'Ankara Sosyal Bilimler Üniversitesi', 'email_domain' => 'asbu.edu.tr'],
            ['name' => 'Ankara Üniversitesi', 'email_domain' => 'ankara.edu.tr'],
            ['name' => 'Ankara Yıldırım Beyazıt Üniversitesi', 'email_domain' => 'aybu.edu.tr'],
            ['name' => 'Ardahan Üniversitesi', 'email_domain' => 'ardahan.edu.tr'],
            ['name' => 'Artvin Çoruh Üniversitesi', 'email_domain' => 'artvin.edu.tr'],
            ['name' => 'Atatürk Üniversitesi', 'email_domain' => 'atauni.edu.tr'],
            ['name' => 'Aydın Adnan Menderes Üniversitesi', 'email_domain' => 'adu.edu.tr'],
            ['name' => 'Balıkesir Üniversitesi', 'email_domain' => 'balikesir.edu.tr'],
            ['name' => 'Bandırma Onyedi Eylül Üniversitesi', 'email_domain' => 'bandirma.edu.tr'],
            ['name' => 'Bartın Üniversitesi', 'email_domain' => 'bartin.edu.tr'],
            ['name' => 'Batman Üniversitesi', 'email_domain' => 'batman.edu.tr'],
            ['name' => 'Bayburt Üniversitesi', 'email_domain' => 'bayburt.edu.tr'],
            ['name' => 'Bilecik Şeyh Edebali Üniversitesi', 'email_domain' => 'bilecik.edu.tr'],
            ['name' => 'Bingöl Üniversitesi', 'email_domain' => 'bingol.edu.tr'],
            ['name' => 'Bitlis Eren Üniversitesi', 'email_domain' => 'bitliseren.edu.tr'],
            ['name' => 'Boğaziçi Üniversitesi', 'email_domain' => 'boun.edu.tr'],
            ['name' => 'Bolu Abant İzzet Baysal Üniversitesi', 'email_domain' => 'ibu.edu.tr'],
            ['name' => 'Burdur Mehmet Akif Ersoy Üniversitesi', 'email_domain' => 'mehmetakif.edu.tr'],
            ['name' => 'Bursa Teknik Üniversitesi', 'email_domain' => 'btu.edu.tr'],
            ['name' => 'Bursa Uludağ Üniversitesi', 'email_domain' => 'uludag.edu.tr'],
            ['name' => 'Çanakkale Onsekiz Mart Üniversitesi', 'email_domain' => 'comu.edu.tr'],
            ['name' => 'Çankırı Karatekin Üniversitesi', 'email_domain' => 'karatekin.edu.tr'],
            ['name' => 'Çukurova Üniversitesi', 'email_domain' => 'cu.edu.tr'],
            ['name' => 'Dicle Üniversitesi', 'email_domain' => 'dicle.edu.tr'],
            ['name' => 'Dokuz Eylül Üniversitesi', 'email_domain' => 'deu.edu.tr'],
            ['name' => 'Düzce Üniversitesi', 'email_domain' => 'duzce.edu.tr'],
            ['name' => 'Ege Üniversitesi', 'email_domain' => 'ege.edu.tr'],
            ['name' => 'Erciyes Üniversitesi', 'email_domain' => 'erciyes.edu.tr'],
            ['name' => 'Erzincan Binali Yıldırım Üniversitesi', 'email_domain' => 'ebyu.edu.tr'],
            ['name' => 'Erzurum Teknik Üniversitesi', 'email_domain' => 'erzurum.edu.tr'],
            ['name' => 'Eskişehir Osmangazi Üniversitesi', 'email_domain' => 'ogu.edu.tr'],
            ['name' => 'Eskişehir Teknik Üniversitesi', 'email_domain' => 'eskisehir.edu.tr'],
            ['name' => 'Fırat Üniversitesi', 'email_domain' => 'firat.edu.tr'],
            ['name' => 'Galatasaray Üniversitesi', 'email_domain' => 'gsu.edu.tr'],
            ['name' => 'Gazi Üniversitesi', 'email_domain' => 'gazi.edu.tr'],
            ['name' => 'Gaziantep İslam Bilim ve Teknoloji Üniversitesi', 'email_domain' => 'gibtu.edu.tr'],
            ['name' => 'Gaziantep Üniversitesi', 'email_domain' => 'gantep.edu.tr'],
            ['name' => 'Gebze Teknik Üniversitesi', 'email_domain' => 'gtu.edu.tr'],
            ['name' => 'Giresun Üniversitesi', 'email_domain' => 'giresun.edu.tr'],
            ['name' => 'Gümüşhane Üniversitesi', 'email_domain' => 'gumushane.edu.tr'],
            ['name' => 'Hacettepe Üniversitesi', 'email_domain' => 'hacettepe.edu.tr'],
            ['name' => 'Hakkari Üniversitesi', 'email_domain' => 'hakkari.edu.tr'],
            ['name' => 'Harran Üniversitesi', 'email_domain' => 'harran.edu.tr'],
            ['name' => 'Hatay Mustafa Kemal Üniversitesi', 'email_domain' => 'mku.edu.tr'],
            ['name' => 'Hitit Üniversitesi', 'email_domain' => 'hitit.edu.tr'],
            ['name' => 'Iğdır Üniversitesi', 'email_domain' => 'igdir.edu.tr'],
            ['name' => 'Isparta Uygulamalı Bilimler Üniversitesi', 'email_domain' => 'isparta.edu.tr'],
            ['name' => 'İnönü Üniversitesi', 'email_domain' => 'inonu.edu.tr'],
            ['name' => 'İskenderun Teknik Üniversitesi', 'email_domain' => 'iste.edu.tr'],
            ['name' => 'İstanbul Medeniyet Üniversitesi', 'email_domain' => 'medeniyet.edu.tr'],
            ['name' => 'İstanbul Teknik Üniversitesi', 'email_domain' => 'itu.edu.tr'],
            ['name' => 'İstanbul Üniversitesi', 'email_domain' => 'istanbul.edu.tr'],
            ['name' => 'İstanbul Üniversitesi-Cerrahpaşa', 'email_domain' => 'iuc.edu.tr'],
            ['name' => 'İzmir Bakırçay Üniversitesi', 'email_domain' => 'bakircay.edu.tr'],
            ['name' => 'İzmir Demokrasi Üniversitesi', 'email_domain' => 'idu.edu.tr'],
            ['name' => 'İzmir Katip Çelebi Üniversitesi', 'email_domain' => 'ikc.edu.tr'],
            ['name' => 'İzmir Yüksek Teknoloji Enstitüsü', 'email_domain' => 'iyte.edu.tr'],
            ['name' => 'Kafkas Üniversitesi', 'email_domain' => 'kafkas.edu.tr'],
            ['name' => 'Kahramanmaraş İstiklal Üniversitesi', 'email_domain' => 'istiklal.edu.tr'],
            ['name' => 'Kahramanmaraş Sütçü İmam Üniversitesi', 'email_domain' => 'ksu.edu.tr'],
            ['name' => 'Karabük Üniversitesi', 'email_domain' => 'karabuk.edu.tr'],
            ['name' => 'Karadeniz Teknik Üniversitesi', 'email_domain' => 'ktu.edu.tr'],
            ['name' => 'Karamanoğlu Mehmetbey Üniversitesi', 'email_domain' => 'kmu.edu.tr'],
            ['name' => 'Kastamonu Üniversitesi', 'email_domain' => 'kastamonu.edu.tr'],
            ['name' => 'Kayseri Üniversitesi', 'email_domain' => 'kayseri.edu.tr'],
            ['name' => 'Kilis 7 Aralık Üniversitesi', 'email_domain' => 'kilis.edu.tr'],
            ['name' => 'Kırıkkale Üniversitesi', 'email_domain' => 'kku.edu.tr'],
            ['name' => 'Kırklareli Üniversitesi', 'email_domain' => 'klu.edu.tr'],
            ['name' => 'Kırşehir Ahi Evran Üniversitesi', 'email_domain' => 'ahievran.edu.tr'],
            ['name' => 'Kocaeli Üniversitesi', 'email_domain' => 'kocaeli.edu.tr'],
            ['name' => 'Konya Teknik Üniversitesi', 'email_domain' => 'ktun.edu.tr'],
            ['name' => 'Kütahya Dumlupınar Üniversitesi', 'email_domain' => 'dumlupinar.edu.tr'],
            ['name' => 'Kütahya Sağlık Bilimleri Üniversitesi', 'email_domain' => 'ksbu.edu.tr'],
            ['name' => 'Malatya Turgut Özal Üniversitesi', 'email_domain' => 'ozal.edu.tr'],
            ['name' => 'Manisa Celal Bayar Üniversitesi', 'email_domain' => 'mcbu.edu.tr'],
            ['name' => 'Mardin Artuklu Üniversitesi', 'email_domain' => 'artuklu.edu.tr'],
            ['name' => 'Marmara Üniversitesi', 'email_domain' => 'marmara.edu.tr'],
            ['name' => 'Mersin Üniversitesi', 'email_domain' => 'mersin.edu.tr'],
            ['name' => 'Mimar Sinan Güzel Sanatlar Üniversitesi', 'email_domain' => 'msgsu.edu.tr'],
            ['name' => 'Muğla Sıtkı Koçman Üniversitesi', 'email_domain' => 'mu.edu.tr'],
            ['name' => 'Munzur Üniversitesi', 'email_domain' => 'munzur.edu.tr'],
            ['name' => 'Muş Alparslan Üniversitesi', 'email_domain' => 'alparslan.edu.tr'],
            ['name' => 'Necmettin Erbakan Üniversitesi', 'email_domain' => 'erbakan.edu.tr'],
            ['name' => 'Nevşehir Hacı Bektaş Veli Üniversitesi', 'email_domain' => 'nevsehir.edu.tr'],
            ['name' => 'Niğde Ömer Halisdemir Üniversitesi', 'email_domain' => 'ohu.edu.tr'],
            ['name' => 'Ondokuz Mayıs Üniversitesi', 'email_domain' => 'omu.edu.tr'],
            ['name' => 'Ordu Üniversitesi', 'email_domain' => 'odu.edu.tr'],
            ['name' => 'Orta Doğu Teknik Üniversitesi', 'email_domain' => 'metu.edu.tr'],
            ['name' => 'Osmaniye Korkut Ata Üniversitesi', 'email_domain' => 'osmaniye.edu.tr'],
            ['name' => 'Pamukkale Üniversitesi', 'email_domain' => 'pau.edu.tr'],
            ['name' => 'Recep Tayyip Erdoğan Üniversitesi', 'email_domain' => 'erdogan.edu.tr'],
            ['name' => 'Sağlık Bilimleri Üniversitesi', 'email_domain' => 'sbu.edu.tr'],
            ['name' => 'Sakarya Uygulamalı Bilimler Üniversitesi', 'email_domain' => 'subu.edu.tr'],
            ['name' => 'Sakarya Üniversitesi', 'email_domain' => 'sakarya.edu.tr'],
            ['name' => 'Samsun Üniversitesi', 'email_domain' => 'samsun.edu.tr'],
            ['name' => 'Selçuk Üniversitesi', 'email_domain' => 'selcuk.edu.tr'],
            ['name' => 'Siirt Üniversitesi', 'email_domain' => 'siirt.edu.tr'],
            ['name' => 'Sinop Üniversitesi', 'email_domain' => 'sinop.edu.tr'],
            ['name' => 'Sivas Bilim ve Teknoloji Üniversitesi', 'email_domain' => 'sivas.edu.tr'],
            ['name' => 'Sivas Cumhuriyet Üniversitesi', 'email_domain' => 'cumhuriyet.edu.tr'],
            ['name' => 'Süleyman Demirel Üniversitesi', 'email_domain' => 'sdu.edu.tr'],
            ['name' => 'Şırnak Üniversitesi', 'email_domain' => 'sirnak.edu.tr'],
            ['name' => 'Tarsus Üniversitesi', 'email_domain' => 'tarsus.edu.tr'],
            ['name' => 'Tekirdağ Namık Kemal Üniversitesi', 'email_domain' => 'nku.edu.tr'],
            ['name' => 'Tokat Gaziosmanpaşa Üniversitesi', 'email_domain' => 'gop.edu.tr'],
            ['name' => 'Trabzon Üniversitesi', 'email_domain' => 'trabzon.edu.tr'],
            ['name' => 'Trakya Üniversitesi', 'email_domain' => 'trakya.edu.tr'],
            ['name' => 'Türk-Alman Üniversitesi', 'email_domain' => 'tau.edu.tr'],
            ['name' => 'Türk-Japon Bilim ve Teknoloji Üniversitesi', 'email_domain' => 'tju.edu.tr'],
            ['name' => 'Uşak Üniversitesi', 'email_domain' => 'usak.edu.tr'],
            ['name' => 'Van Yüzüncü Yıl Üniversitesi', 'email_domain' => 'yyu.edu.tr'],
            ['name' => 'Yalova Üniversitesi', 'email_domain' => 'yalova.edu.tr'],
            ['name' => 'Yıldız Teknik Üniversitesi', 'email_domain' => 'yildiz.edu.tr'],
            ['name' => 'Yozgat Bozok Üniversitesi', 'email_domain' => 'bozok.edu.tr'],
            ['name' => 'Zonguldak Bülent Ecevit Üniversitesi', 'email_domain' => 'beun.edu.tr'],
        ];

        foreach ($universities as $university) {
            University::create($university);
        }
    }
} 